 extend type Query {
    getUser(id: Int!): User
    getAllUsers:[User]
  }
 extend type Mutation {
    createUser(firstName: String!, lastName: String, age: Int!, email: String): Boolean!
    deleteUser(id: Int!) : Boolean!
  }

  type User {
    id: Int!
    firstName: String!
    lastName: String!
    age: Int!
    email: String!
    createDate: Date!
    role: Role
  }