 extend type Query {
    getUser(id: Int!): User
    getAllUsers:[User]
    getMe: User
  }
 extend type Mutation {
    createUser(firstName: String!, lastName: String, age: Int!, email: String, password: String): Boolean!
    deleteUser(id: Int!) : Boolean!
    login(email: String!, password: String!): User
  }

  type User {
    id: Int!
    firstName: String!
    lastName: String!
    age: Int!
    email: String!
    password: String!
    createDate: Date!
    role: Role
  }